---
- name: Automatically hide the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  notify: Restart Dock

- name: Disable automatic spelling correction
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

- name: Disable natural scrolling
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false
